### ISSUE TITLE
Проверочные примеры алгоритма сжатия

### ISSUE THREAD

**Issue by makavity** [bcrypto/belt#5]
Добрый день!
В алгоритме сжатия имеем входное слово длины 512, и два выходных - длины 128 и 256, что не соответствует размерности данных в проверочном примере из таблицы А-8.
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/5614215/154072979-61ef0c97-a527-45b4-85d9-e9540f3149b2.png">
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/5614215/154073229-1407a783-242c-47ad-bbb0-36ed9948cfec.png">

**Comment by agievich** [comment]
Ошибка устранена в https://github.com/bcrypto/belt/commit/91a04760504e2db03014dd22ebfd77a32b5f2a50: в таблице А.8 слово X продолжено до 512 битов.
